### ISSUE TITLE
java.lang.ClassCastException with four or more effects

### ISSUE THREAD

**Issue by tscholak** [edmundnoble/atlast#1]
There are runtime issues when four or more effects are used, e.g.
```
java.lang.ClassCastException: someEffect cannot be cast to someOtherEffect
```
thrown by https://github.com/edmundnoble/atlast/blob/master/core/shared/src/main/scala/atlast/%3C%3D.scala#L7

To resolve this, I believe
https://github.com/edmundnoble/atlast/blob/master/core/shared/src/main/scala/atlast/ATL.scala#L15-L16 should read
```scala
def append[L, R, F[_]](le: InterpretersTo[F, L], re: InterpretersTo[F, R]): InterpretersTo[F, Fx.Append[L, R]] =
      InterpretersTo[F, Fx.Append[L, R]](re.coll ++ le.coll)
```
instead of
```scala
def append[L, R, F[_]](le: InterpretersTo[F, L], re: InterpretersTo[F, R]): InterpretersTo[F, Fx.Append[L, R]] =
      InterpretersTo[F, Fx.Append[L, R]](le.coll ++ re.coll)
```
to make sure that the vector `coll` is consistently reversed.

I applied that to my local branch and the issues were gone.

**Comment by edmundnoble** [comment]
That's definitely the case; sorry, unsafe stuff and no tests. This isn't really a library as much as an experiment.

**Comment by edmundnoble** [comment]
Fix pushed. Thanks!
